# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anemone/anemone/c/tcp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anemone/anemone/c/tcp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anemone/anemone/c/tcp/CMakeFiles /home/anemone/anemone/c/tcp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anemone/anemone/c/tcp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named service

# Build rule for target.
service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 service
.PHONY : service

# fast build rule for target.
service/fast:
	$(MAKE) -f CMakeFiles/service.dir/build.make CMakeFiles/service.dir/build
.PHONY : service/fast

#=============================================================================
# Target rules for targets named tcphelp

# Build rule for target.
tcphelp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcphelp
.PHONY : tcphelp

# fast build rule for target.
tcphelp/fast:
	$(MAKE) -f CMakeFiles/tcphelp.dir/build.make CMakeFiles/tcphelp.dir/build
.PHONY : tcphelp/fast

tcpclient.o: tcpclient.cpp.o

.PHONY : tcpclient.o

# target to build an object file
tcpclient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcpclient.cpp.o
.PHONY : tcpclient.cpp.o

tcpclient.i: tcpclient.cpp.i

.PHONY : tcpclient.i

# target to preprocess a source file
tcpclient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcpclient.cpp.i
.PHONY : tcpclient.cpp.i

tcpclient.s: tcpclient.cpp.s

.PHONY : tcpclient.s

# target to generate assembly for a file
tcpclient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcpclient.cpp.s
.PHONY : tcpclient.cpp.s

tcphelp.o: tcphelp.c.o

.PHONY : tcphelp.o

# target to build an object file
tcphelp.c.o:
	$(MAKE) -f CMakeFiles/tcphelp.dir/build.make CMakeFiles/tcphelp.dir/tcphelp.c.o
.PHONY : tcphelp.c.o

tcphelp.i: tcphelp.c.i

.PHONY : tcphelp.i

# target to preprocess a source file
tcphelp.c.i:
	$(MAKE) -f CMakeFiles/tcphelp.dir/build.make CMakeFiles/tcphelp.dir/tcphelp.c.i
.PHONY : tcphelp.c.i

tcphelp.s: tcphelp.c.s

.PHONY : tcphelp.s

# target to generate assembly for a file
tcphelp.c.s:
	$(MAKE) -f CMakeFiles/tcphelp.dir/build.make CMakeFiles/tcphelp.dir/tcphelp.c.s
.PHONY : tcphelp.c.s

tcpservice.o: tcpservice.cpp.o

.PHONY : tcpservice.o

# target to build an object file
tcpservice.cpp.o:
	$(MAKE) -f CMakeFiles/service.dir/build.make CMakeFiles/service.dir/tcpservice.cpp.o
.PHONY : tcpservice.cpp.o

tcpservice.i: tcpservice.cpp.i

.PHONY : tcpservice.i

# target to preprocess a source file
tcpservice.cpp.i:
	$(MAKE) -f CMakeFiles/service.dir/build.make CMakeFiles/service.dir/tcpservice.cpp.i
.PHONY : tcpservice.cpp.i

tcpservice.s: tcpservice.cpp.s

.PHONY : tcpservice.s

# target to generate assembly for a file
tcpservice.cpp.s:
	$(MAKE) -f CMakeFiles/service.dir/build.make CMakeFiles/service.dir/tcpservice.cpp.s
.PHONY : tcpservice.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... service"
	@echo "... tcphelp"
	@echo "... tcpclient.o"
	@echo "... tcpclient.i"
	@echo "... tcpclient.s"
	@echo "... tcphelp.o"
	@echo "... tcphelp.i"
	@echo "... tcphelp.s"
	@echo "... tcpservice.o"
	@echo "... tcpservice.i"
	@echo "... tcpservice.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

